import { IDictionary } from '../../interfaces/IDictionary';

export const DicionarioMotivosOcorrencias: IDictionary = {
  '02': {
    '00': 'Ocorrência aceita',
    '01': 'Código do banco inválido',
    '04': 'Código do movimento não permitido para a carteira',
    '15': 'Características da cobrança incompatíveis',
    '17': 'Data de vencimento anterior a data de emissão',
    '21': 'Espécie de Título inválido',
    '24': 'Data da emissão inválida',
    '27': 'Valor/taxa de juros mora inválido',
    '38': 'Prazo para protesto/negativação inválido',
    '39': 'Pedido para protesto/negativação não permitido para o título',
    '43': 'Prazo para baixa e devolução inválido',
    '45': 'Nome do pagador inválido',
    '46': 'Tipo/num. de inscrição do pagador inválido',
    '47': 'Endereço do pagador não informado',
    '48': 'CEP inválido',
    '50': 'CEP referente a banco correspondente',
    '53': 'Nº de incrição do pagador/avalista inválidos',
    '54': 'Pagador/avalista não informados',
    '67': 'Débito automático agendado',
    '68': 'Débito não agendado - erro nos dados de remessa',
    '69': 'Débito não agendado - pagador não consta no cadastro de autorizante',
    '70': 'Débito não agendado - beneficiário não autorizado pelo pagador',
    '71': 'Débito não agendado - beneficiário não participa da modalidade de déb. automático',
    '72': 'Débito não agendado - código de moeda diferente de R$',
    '73': 'Débito não agendado - data de vencimento inválida/vencida',
    '75': 'Débito não agendado - tipo do número de incrição do pagador debitado inválido',
    '76': 'Pagador eletrônico DDA',
    '86': 'Seu número do documento inválido',
    '89': 'E-mail pagador não enviado - título com débito automático',
    '90': 'E-mail pagador não enviado - título de cobrança sem registro',
  },

  '03': {
    '02': 'Código do registro detalhe inválido',
    '03': 'Código da ocorrência inválida',
    '04': 'Código de ocorrência não permitida para a carteira',
    '05': 'Código de ocorrência não numérico',
    '07': 'Agência/conta/dígito inválido',
    '08': 'Nosso número inválido',
    '09': 'Nosso número duplicado',
    '10': 'Carteira inválida',
    '13': 'Identificação da emissão do boleto inválida',
    '16': 'Data de vencimento inválida',
    '18': 'Vencimento fora do prazo de operação',
    '20': 'Valor do título inválido',
    '21': 'Espécie do título inválida',
    '22': 'Espécie não permitida para a carteira',
    '24': 'Data de emissão inválida',
    '28': 'Código do desconto inválido',
    '38': 'Prazo para protesto/negativação inválido',
    '44': 'Agência beneficiário não prevista',
    '45': 'Nome do pagador não informado',
    '46': 'Tipo/número de incrição do pagador inválidos',
    '47': 'Endereço do pagador não informado',
    '48': 'CEP inválido',
    '50': 'CEP irregular - Banco Correspondente',
    '63': 'Entrada para título já cadastrado',
    '65': 'Limite excedido',
    '66': 'Número autorização inexistente',
    '68': 'Débito não agendado - erro nos dados da remessa',
    '69': 'Débito não agendado - pagador não consta no cadastro de autorizante',
    '70': 'Débito não agendado - beneficiário não autorizado pelo pagador',
    '71': 'Débito não agendado - Beneficiário não participa do débito automático',
    '72': 'Débito não agendado - Código de moeda diferente de R$',
    '73': 'Débito não agendado - Data de vencimento inválida',
    '74': 'Débito não agendado - Conforme pedido. Título não registrado.',
    '75': 'Débito não agendado - Tipo de número de inscrição do debitado inválido',
  },

  '06': {
    '00': 'Título pago com dinheiro',
    '15': 'Título pago com cheque',
    '18': 'Pagamento parcial',
    '42': 'Rateio não efetuado',
  },

  '09': {
    '00': 'Ocorrência aceita',
    '10': 'Baixa comandada pelo cliente',
  },

  '10': {
    '00': 'Baixado conforme instruções da agência',
    '14': 'Título protestado',
    '15': 'Título excluído',
    '16': 'Título baixado pelo banco por decurso prazo',
    '17': 'Título Baixado Transferido Carteira',
    '20': 'Título Baixado e transferido para desconto',
  },

  '15': {
    '00': 'Título pago com dinheiro',
    '15': 'Título pago com cheque',
  },

  '17': {
    '00': 'Título pago com dinheiro',
    '15': 'Título pago com cheque',
  },

  '24': {
    48: 'CEP inválido',
  },

  '27': {
    '04': 'Código de ocorrência não permitida para a carteira',
    '07': 'Agência/conta/dígito inválidos',
    '08': 'Nosso número inválido',
    '10': 'Carteira inválida',
    '15': 'Carteira/Agência/Conta/Nosso Número inválidos',
    '40': 'Título com ordem de protesto emitido',
    '42': 'Código para baixa/devolução via Tele Bradesco inválido',
    '60': 'Movimento para título não cadastrado',
    '77': 'Transferência para desconto não permitida para a carteira',
    '85': 'Título com pagamento vinculado',
  },

  '28': {
    '02': 'Tarifa de permanência título cadastrado',
    '03': 'Tarifa de sustação/Excl Negativação',
    '04': 'Tarifa de protesto/Incl Negativação',
    '05': 'Tarifa de outras instruções',
    '06': 'Tarifa de outras ocorrências',
    '08': 'Custas de protestos',
    '12': 'Tarifa de registro',
    '13': 'Tarifa título pago no Bradesco',
    '14': 'Tarifa título pago compensação',
    '15': 'Tarifa título baixado não pago',
    '16': 'Tarifa alteração de vencimento',
    '17': 'Tarifa concessão abatimento',
    '18': 'Tarifa cancelamento de abatimentos',
    '19': 'Tarifa concessão de desconto',
    '20': 'Tarifa cancelamento de desconto',
    '21': 'Tarifa título pago cics',
    '22': 'Tarifa título pago internet',
    '23': 'Tarifa título pago term. gerencial serviços',
    '24': 'Tarifa título pago Pág-Contas',
    '25': 'Tarifa título pago Fone Fácil',
    '26': 'Tarifa título Déb Postagem',
    '27': 'Tarifa impressão de títulos pendentes',
    '28': 'Tarifa título pago BDN',
    '29': 'Tarifa título pago Term. Multi Função',
    '30': 'Impressão de títulos baixados',
    '31': 'Impressão de títulos pagos',
    '32': 'Tarifa título pago Pagfor',
    '33': 'Tarifa reg/pgto - guichê caixa',
    '34': 'Tarifa título pago retaguarda',
    '35': 'Tarifa título pago Subcentro',
    '36': 'Tarifa título pago cartão de crédito',
    '37': 'Tarifa título pago Comp Eletrônica',
    '38': 'Tarifa título Baix. Pg. Cartório',
    '39': 'Tarifa título baixado acerto BCO',
    '40': 'Baixa registro em duplicidade',
    '41': 'Tarifa título baixado decurso prazo',
    '42': 'Tarifa título baixadi Judicialmente',
    '43': 'Tarifa título baixado via remessa',
    '44': 'Tarifa título baixado rastreamento',
    '45': 'Tarifa título baixado conf. pedido',
    '46': 'Tarifa título baixado protestado',
    '47': 'Tarifa título baixado p/ devolução',
    '48': 'Tarifa título baixado franco pgto',
    '49': 'Tarifa título baixado SUST/RET/CARTÓRIO',
    '50': 'Tarifa título baixado SUS/SEM/REM/CARTÓRIO',
    '51': 'Tarifa título transferido desconto',
    '52': 'Cobrado baixa manual',
    '53': 'Baixa por acerto cliente',
    '54': 'Tarifa baixa por contabilidade',
    '55': 'Tr. tentativa cons deb aut',
    '56': 'Tr. credito online',
    '57': 'Tarifa reg/pagto Bradesco expresso',
    '58': 'Tarifa emissão papeleta',
    '59': 'Tarifa fornec papeleta semi preenchida',
    '60': 'Acondicionador de papeletas (RPB)S',
    '61': 'Acond. de papeletas (RPB)s PERSONAL',
    '62': 'Papeleta formulário branco',
    '63': 'Formulário A4 Serrilhado',
    '64': 'Fornecimento de softwares transmiss',
    '65': 'Fornecimento de softwares consulta',
    '66': 'Fornecimento Micro Completo',
    '67': 'Fornecimento MODEN',
    '68': 'Fornecimento de máquina FAX',
    '69': 'Fornecimento de máquinas óticas',
    '70': 'Fornecimento de impressoras',
    '71': 'Reativação de título',
    '72': 'Alteração de produto negociado',
    '73': 'Tarifa emissão de contra recibo',
    '74': 'Tarifa emissão 2ª via papeleta',
    '75': 'Tarifa regravação arquivo retorno',
    '76': 'Arq. Títulos a vencer mensal',
    '77': 'Listagem auxiliar de crédito',
    '78': 'Tarifa cadastro cartela instrução permanente',
    '79': 'Canalização de crédito',
    '80': 'Cadastro de Mensagem Fixa',
    '81': 'Tarifa representação automática título',
    '82': 'Tarifa registro título Déb. Automático',
    '83': 'Tarifa rateio de crédito',
    '84': 'Emissão papeleta sem valor',
    '85': 'Sem uso',
    '86': 'Cadastro de reembolso de diferença',
    '87': 'Relatório fluxo de pagto',
    '88': 'Emissão extrato mov. Carteira',
    '89': 'Mensagem campo local de pagamento',
    '90': 'Cadastro concessionária serv. publ.',
    '91': 'Classif. extrato conta corrente',
    '92': 'Contabilidade especial',
    '93': 'Realimentação de pagamento',
    '94': 'Repasse de créditos',
    '96': 'Tarifa reg. Pgto outras mídias',
    '97': 'Tarifa reg/pgtp - Net Empresa',
    '98': 'Tarifa título pago vencido',
    '99': 'TR Título baixado por decurso prazo',

    '100': 'Arquivo Retorno Antecipado',
    '101': 'Arq. Retorno Hora/Hora',
    '102': 'TR. Agendamento Débito Automático',
    '105': 'TR. Agendamento rat. Crédito',
    '106': 'TR. Emissão aviso rateio',
    '107': 'Extrato de protesto',
  },

  '29': {
    78: 'Pagador alega que faturamento é indevido',
    95: 'Pagador aceita/reconhece o faturamento',
  },

  '30': {
    '01': 'Código do banco inválido',
    '04': 'Código de ocorrência não permitido para a carteira',
    '05': 'Código da ocorrência não numérico',
    '08': 'Nosso número inválido',
    '15': 'Característica de cobrança incompatível',
    '16': 'Data de vencimento inválido',
    '17': 'Data de vencimento anterior a data de emissão',
    '18': 'Vencimento fora do prazo de operação',
    '24': 'Data de emissão inválida',
    '26': 'Código de juros de mora inválida',
    '27': 'Valor/taxa de juros de mora inválido',
    '28': 'Código de desconto inválido',
    '29': 'Valor do desconto maior/igual ao valor do título',
    '30': 'Desconto a conceder não confere',
    '31': 'Concessão de desconto já existente',
    '32': 'Valor do IOF inválido',
    '33': 'Valor do abatimento inválido',
    '34': 'Valor do abatimento maior/igual ao valor do título',
    '38': 'Prazo para protesto/negativação inválido',
    '39': 'Pedido para protesto/negativação não permitido para o título',
    '40': 'Título com ordem/pedido de protesto/negativação emitido',
    '42': 'Código para baixa/devolução inválido',
    '46': 'Tipo/número de incrição do pagador inválidos',
    '48': 'CEP inválido',
    '53': 'Tipo/número de inscrição do pagador/avalista inválidos',
    '54': 'Pagador/avalista não informados',
    '57': 'Código de multa inválido',
    '58': 'Data da multa inválida',
    '60': 'Movimento para título não cadastrado',
    '79': 'Data de juros de mora inválida',
    '80': 'Data do desconto inválida',
    '85': 'Título com pagamento vinculado',
    '88': 'E-mail pagador não lido do prazo 5 dias',
    '91': 'E-mail pagador não recebido',
  },

  '32': {
    '01': 'Código do banco inválido',
    '02': 'Código do registro detalhe inválido',
    '04': 'Código de ocorrência não permitido para a carteira',
    '05': 'Código de ocorrência não numérico',
    '07': 'Agência/Conta/Dígito inválidos',
    '08': 'Nosso número inválido',
    '10': 'Carteira inválida',
    '15': 'Características da cobrança incompatíveis',
    '16': 'Data de vencimento inválida',
    '17': 'Data de vencimento anterior a data de emissão',
    '18': 'Vencimento fora do prazo de operação',
    '20': 'Valor do título inválido',
    '21': 'Espécie do título inválida',
    '22': 'Espécie não permitida para a carteira',
    '24': 'Data de emissão inválida',
    '28': 'Código de desconto via Telebradesco inválido',
    '29': 'Valor do desconto maior/igual ao valor do título',
    '30': 'Desconto a conceder não confere',
    '31': 'Concessão de desconto - Já existe desconto anterior',
    '33': 'Valor do abatimento inválido',
    '34': 'Valor do abatimento maior/igual ao valor do título',
    '36': 'Concessão abatimento - Já existe abatimento anterior',
    '38': 'Prazo para protesto/negativação inválido',
    '39': 'Pedido para protesto/negativação não permitido para o título',
    '40': 'Título com ordem/pedido de protesto/negativação emitido',
    '41': 'Pedido de sustação/excl p/ título sem intrução de protesto/negativação',
    '42': 'Código para baixa/devolução inválido',
    '45': 'Nome do pagador não informado',
    '46': 'Tipo/número de inscrição do pagador inválidos',
    '47': 'Endereço do pagador não informado',
    '48': 'CEP inválido',
    '50': 'CEP referente a um banco correspondente',
    '53': 'Tipo de inscrição do pagador avalista inválidos',
    '60': 'Movimentação para título não cadastrado',
    '85': 'Título com pagamento vinculado',
    '86': 'Seu número inválido',
    '94': 'Título penhorado - Instrução não liberada pela Agência',
    '97': 'Instrução não permitida título negativado',
    '98': 'Inclusão bloqueada face a determinação judicial',
    '99': 'Telefone beneficiário não informado/inconsistente',
  },

  '35': {
    81: 'Tentativas esgotadas, baixado',
    82: 'Tentativas esgotadas, pendente',
    83: 'Cancelado pelo pagador e mantido pendente, conforme negociação',
    84: 'Cancelado pelo pagador e baixado, conforme negociação',
  },
};
