import { IDictionary } from "../../interfaces/IDictionary";

export const DicionarioOcorrencias: IDictionary = {
  '02': 'Entrada confirmada',
  '03': 'Entrada rejeitada',
  '06': 'Liquidação normal',
  '09': 'Baixado automático via arquivo',
  '10': 'Baixado conforme instruções da agência',
  '11': 'Em Ser - Arquivo de títulos pendentes',
  '12': 'Abatimento concedido',
  '13': 'Abatimento cancelado',
  '14': 'Vencimeno Alterado',
  '15': 'Liquidação em cartório',
  '16': 'Título pago em cheque',
  '17': 'Liquidação após baixa ou título não registrado',
  '18': 'Acerto de depositária',
  '19': 'Confirmação receb. Inst. de Protesto',
  '20': 'Confirmação receb. Inst. Sustentação de Protesto',
  '21': 'Acerto do controle do participante',
  '22': 'Título com pagamento cancelado',
  '23': 'Entrada do título em cartório',
  '24': 'Entrada rejeitada por CEP irregular',
  '25': 'Confirmação Receb. Inst. de Protesto Falimentar',
  '27': 'Baixa rejeitada',
  '28': 'Débito de tarifas/custas',
  '29': 'Ocorrências do Pagador',
  '30': 'Alteração de outros dados rejeitados (verificar motivo)',
  '32': 'Instrução rejeitada',
  '33': 'Confirmação pedido alteração de outros dados',
  '34': 'Retirado de cartório e manutenção carteira',
  '35': 'Desagendamento do débito automático (verif. motivo)',
  '40': 'Estorno de pagamento',
  '55': 'Sustado judicial',
  '68': 'Acerto dos dados de rateio de crédito',
  '69': 'Cancelamento dos dados do rateio',
  '73': 'Confirmação Receb. Pedido de negativação',
  '74': 'Confirmação pedido de exclusão de negativação',
};
